### PR TITLE
Convert to TypeScript

### PR DESCRIPTION
**Pull request by visvirial**
I have converted the source code into TypeScript.
Please review&merge it.

### CODE REVIEW

**Comment by visvirial** [comment]
FYI: current `index.d.ts` does not support `encode().bytes` and `decode().bytes` props, which indicates the actual number of bytes to be encoded/decoded. (although, I don't think it is a good implementation (since these functions should not have a state) but it cannot be removed for backward compatibility)

**Comment by junderw** [comment]
A few comments:

1. As a policy, bitcoinJS commits the JS and type definition files to prevent Microsoft from doing bad things with transpiling.
2. Removing runtime type checks is bad since we have no guarantee that everyone using the library is definitely using TypeScript.

**Comment by junderw** [comment]
Closed in favor of #11 

I added you as co-author to the commit.

Thanks for your help!

**Comment by visvirial** [comment]
Do you mean that the following things are fulfilled, you will be willing to merge the TypeScript code? Or, you are not about to convert to TypeScript anymore?
- Commit generated JavaScript code and type definition code (`index.js` and `index.d.ts`)
- Revive type check logics.

**Comment by junderw** [comment]
There were a couple of other issues I found:

- No build script
- No formatter
- (for not committing JS) No prePublishOnly script for publishing
- (for committing JS) No git diff check script for prepublish

But to be honest, this library is extremely simple, so switching over to TypeScript completely serves only one real purpose:

- To generate index.d.ts so that people consuming the library can use it with TypeScript

(You could argue that maybe TypeScript based tooling for tests is more desirable, but again, this library is not going to be changed besides bugfixes.)

Since you figured out the `bytes` problem, the index.d.ts is now perfect. Spending any more time on trying to get the TypeScript build process and formatters and prepublish scripts etc. is kind of a waste of time now.

If you create a new PR with TypeScript implementation and the problems I mentioned above fixed I will look at it, but imo I think the index.d.ts that was generated from this PR is enough.

If this library was going to add more features, maybe it would be better to have TypeScript, but since this library is basically finished, index.d.ts should be fine.

**Pull request closed without merging**
